version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/builder"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: all
    commit-message:
      prefix: "deps: "
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    commit-message:
      prefix: "deps(actions): "
  - package-ecosystem: docker
    directory: "**/Dockerfile"
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    commit-message:
      prefix: "deps: "
