name: dependabot-build
on:
  workflow_run:
    workflows: ["is-dependabot"]
    types:
      - completed

# https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/docker-image.yml
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
