name: is-dependabot
on:
  push:
    branches: snapshot

# Dependabot doesn't have access to secrets
# when they instigate a standard PR github action.
# https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
# This then triggers dependabot-build.yml
jobs:
  dependabot-build-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: Dependabot workflow Trigger
    steps:
    - name: Find associated PR
      uses: jwalton/gh-find-current-pr@v1
      id: findpr
      with:
        github-token: ${{ github.token }}
        state: open
        sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
    - name: Grab Dependabot metadata
      id: depbot-metadata
      continue-on-error: true
      uses: dependabot/fetch-metadata@v1
    - name: Repository Dispatch Event
      uses: actions/github-script@v7
      env:
        evt_payload: |
          {
            "branch" : "${{ github.head_ref }}",
            "sha": "${{ github.event.pull_request.head.sha }}",
            "pull_request": "${{ steps.findpr.outputs.pr }}"
          }
        evt_type: "dependabot-build"
      with:
        script: |
          const { evt_payload , evt_type } = process.env
          console.log(evt_payload)
          github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: evt_type,
              client_payload: JSON.parse(evt_payload)
          })
