name: is-dependabot
on:
  push:
    branches: snapshot

# Dependabot doesn't have access to secrets
# when they instigate a standard PR github action.
# https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
# This then triggers dependabot-build.yml
jobs:
  dependabot-build-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: Dependabot workflow Trigger
    steps:
    - name: Find associated PR
      uses: jwalton/gh-find-current-pr@v1
      id: findpr
      with:
        github-token: ${{ github.token }}
        state: open
        sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
    - name: Grab Dependabot metadata
      id: depbot-metadata
      continue-on-error: true
      uses: dependabot/fetch-metadata@v1
    - name: Repository Dispatch Event
      uses: quotidian-ennui/actions-olio/repo-dispatch@main
      with:
        event_type: "dependabot-build"
        token: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ github.event.pull_request.head.sha }}
        ref: ${{ github.head_ref }}
        event_detail: |
         {
            "dependabot_update_type": "${{ steps.depbot-metadata.outputs.update-type || 'unknown' }}"
         }
