name: dependabot-build
on:
  repository_dispatch:
    types:
      - dependabot-build

jobs:
  build:
    uses: ./.github/workflows/docker-image.yml
    with:
      target_branch: ${{ github.event.client_payload.branch }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
