name: docker-image

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        description: 'The branch to checkout and work-on'
        type: string
      registry_push:
        required: false
        description: 'Push to the registry'
        default: true
        type: boolean
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_TOKEN:
        required: true

jobs:
  docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # nicer logging when you look at the workflow run
        docker_target: ['eclipse-temurin', 'liberica-alpine', 'corretto', 'graalvm']
        include:
          - docker_target: eclipse-temurin
            docker_tag_suffix: ''
            docker_platform: linux/amd64,linux/arm64
          - docker_target: liberica-alpine
            docker_tag_suffix: -liberica-alpine
            docker_platform: linux/amd64,linux/arm64
          - docker_target: corretto
            docker_tag_suffix: -corretto
            docker_platform: linux/amd64,linux/arm64
          - docker_target: graalvm
            docker_tag_suffix: -graalvm
            docker_platform: linux/amd64,linux/arm64

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        ref: ${{ inputs.target_branch }}
    - name: docker-build-push
      uses: quotidian-ennui/actions-olio/docker-image-builder@main
      with:
        registry_push: ${{ inputs.registry_push }}
        dockerfile: ${{ matrix.docker_target }}/Dockerfile
        image_tag_suffix: ${{ matrix.docker_tag_suffix }}
        image_platforms: ${{ matrix.docker_platform }}
        dockerhub_image_name: lewinc/interlok-base
        dockerhub_user: ${{ secrets.DOCKER_USER }}
        dockerhub_token: ${{ secrets.DOCKER_TOKEN }}
