name: docker-latest-snapshot

on:
  workflow_dispatch:
  push:
    branches: snapshot
  schedule:
    - cron: '15 05 * * SUN'

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/docker-image.yml
    with:
      target_branch: ${{ github.head_ref }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}