name: docker-hub-description

on:
  push:
    branches:
    - snapshot
    paths:
    - "README.md"

jobs:
  docker-hub-description:
    name: Update Docker Hub description
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: lewinc/interlok-base
